# Generated by Django 5.1.6 on 2025-02-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soap',
            new_name='Product',
        ),
    ]
