# Generated by Django 5.1.6 on 2025-03-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shampoo_bar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Shampoo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_shampoo', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='soap',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Soap'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_soap', to='products.product'),
        ),
    ]
