# Generated by Django 5.1.6 on 2025-03-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_shampoo_bar_product_soap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shampoo_bar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='soap',
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_items',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
